name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy Mkdocs
        env:
          DOC_DEPLOY_IP: ${{ secrets.DOC_DEPLOY_IP }}
          DOC_DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DOC_DEPLOY_SSH_PRIVATE_KEY }}
          DOC_DEPLOY_USER: ${{ secrets.DOC_DEPLOY_USER }}
        run: |
            pip3 install mkdocs mkdocs-material
            mkdocs build
            zip -rq mkdocs.zip doc
            echo "$DOC_DEPLOY_SSH_PRIVATE_KEY" > key
            chmod 600 key
            ssh -i key -o StrictHostKeyChecking=no $DOC_DEPLOY_USER@$DOC_DEPLOY_IP 'rm -rf /opt/landing-docker/docs/files/*'
            scp -i key -o StrictHostKeyChecking=no mkdocs.zip $DOC_DEPLOY_USER@$DOC_DEPLOY_IP:/opt/landing-docker/docs/files/
            ssh -i key -o StrictHostKeyChecking=no $DOC_DEPLOY_USER@$DOC_DEPLOY_IP 'cd /opt/landing-docker/docs/files && unzip -q mkdocs.zip && rm mkdocs.zip'
